character:
  - name: ルシティ
    characteristics:
      name:
        formal name: ルシティ・セヨカハーリッツェー
        origin of name: フィンランド語でを意味する 
        origin of formal name: フィンランド語で統べる者を意味する se joka hallitsee
      inherent:
        race: ホムンクルス
        gender: 男性
        age: 17
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        pre-independence affaiers:
          - 
        post-independence affaiers:
          - 
        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:
        trauma: |

  - name: ヴァルミスターヤ
    characteristics:
      name:
        formal name: ヴァルミスターヤ・セヨカハーリッツェー
        origin of name: フィンランド語で制作者を意味する valmistaja
        origin of formal name: フィンランド語で統べる者を意味する se joka hallitsee
      inherent:
        race: ホムンクルス
        gender: 男性
        age: 17
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        pre-independence affaiers:
          - 
        post-independence affaiers:
          - 
        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:
        trauma: |

